### PR TITLE
Auto Twitter Post On release #1825

### PR DESCRIPTION
**Pull request by shivam-Purohit**
referencing [issue ](https://github.com/intelowlproject/IntelOwl/issues/1825)#1825

Publish github actions for automating twitter post on new releases

### CODE REVIEW

**Comment by shivam-Purohit** [comment]
Hey, I am just testing the feature now in a separate repo. Please ignore all the commits for now.
I already tested it using a normal github action working fine but have to make some changes for publishing it.

**Comment by shivam-Purohit** [comment]
hey @mlodic sorry I was out of town for a week. I think this should work now, I had to add composite action as it does not support Python. I also added test.yml to manually trigger the action for testing purpose.

**Comment by mlodic** [comment]
I was out too so sorry for the delay!

I published the action! https://github.com/marketplace/actions/publish-to-twitter
Would you like to add it in IntelOwl?

**Comment by shivam-Purohit** [comment]
Yes sure. But I wanted to test it if it works as intended or if anything is wrong in the code.

**Pull request merged**
